languageCode: en-us
title: G. Hunter Anderson
theme: hugo-coder
baseURL: https://www.ghunteranderson.com/
paginate: 20

# Style list: https://help.farbox.com/pygments.html
pygmentsstyle: friendly
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

disqusShortname: ghunteranderson

params:
  author: G. Hunter Anderson
  info: |
    Software Architect | Doctoral Student
  description: Hunter Anderson's personal website
  keywords: blog,developer,programmer,java,phd
  avatarurl: /images/me.jpg

  favicon_32: /imgages/favicon-32x32.png
  favicon_16: /imgages/favicon-16x16.png

  colorScheme: light
  hidecolorschemetoggle: true

  customCSS:
  - "css/tweaks.css"

  footercontent: '"... on the shoulders of giants."'

  hidecredits: false
  hidecopyright: true

  rtl: false
  math: true

  goatCounter:
    code: ghunteranderson

  social:
  - name: Github
    icon: fa fa-github fa-2x
    weight: 1
    url: https://github.com/ghunteranderson/
  - name: LinkedIn
    icon: fa fa-linkedin fa-2x
    weight: 2
    url: https://linkedin.com/in/ghunteranderson/
  - name: Email
    icon: fas fa-envelope fa-2x
    weight: 3
    url: mailto:hunter@txstate.edu

menu:
  main:
  - name: About Me
    weight: 1
    url: /#aboutme
  - name: Research
    weight: 2
    url: /#research
  - name: Teaching
    weight: 3
    url: /#teaching
  - name: Service
    weight: 4
    url: /#service
  - name: Blog
    weight: 5
    url: /posts/
