context:
  deploy-preview:
    command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

redirects:
- from = "/projects/jsemver"
  to = "https://github.com/ghunteranderson/jsemver"
  status = 302
  force = true
